name: Playwright API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Newman HTML reporter
        run: npm install --save-dev newman-reporter-html

      - name: Install Playwright
        run: npx playwright install

      - name: Start mock server
        run: |
          nohup node API_Tests/mocks/server.js &
          sleep 2

      - name: Run Playwright tests and generate HTML report
        run: npx playwright test API_Tests/playwright --reporter=html

      - name: Run Postman Collection with Newman
        run: npm run api-test

      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
